language: node_js
node_js:
  - "10"

cache:
  npm: true

install:
  - yarn add --global @vue/cli @quasar/cli
  - yarn install
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./.travis.sh; fi'

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn test; fi'

deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN
  verbose: true
  on:
    master: true
